name: CI

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]

permissions:
    contents: write

jobs:
    build-and-deploy:
        name: Build and deploy
        timeout-minutes: 15
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.32.2

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Create dist
              run: pnpm create-dist

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist
